__title__ = 'swiftype_app_search'
__description__ = 'A Deprecated API client for Swiftype App Search - Use new elastic-app-search package instead.'
__url__ = 'https://github.com/swiftype/swiftype-app-search-python'
__version__ = '0.6.1'
__author__ = 'Swiftype'
__author_email__ = 'eng@swiftype.com'
